//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Builds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Builds()
        {
            this.BuildCaseCooling = new HashSet<BuildCaseCooling>();
            this.BuildRAMs = new HashSet<BuildRAMs>();
            this.BuildStorages = new HashSet<BuildStorages>();
        }
    
        public int BuildID { get; set; }
        public string BuildName { get; set; }
        public int GPU_ID { get; set; }
        public int CPU_ID { get; set; }
        public int Motherboard_ID { get; set; }
        public int CPUCooling_ID { get; set; }
        public int PowerSupply_ID { get; set; }
        public int Case_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildCaseCooling> BuildCaseCooling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildRAMs> BuildRAMs { get; set; }
        public virtual Cases Cases { get; set; }
        public virtual CPUCooling CPUCooling { get; set; }
        public virtual CPUs CPUs { get; set; }
        public virtual GPUs GPUs { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual PowerSupplies PowerSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildStorages> BuildStorages { get; set; }
    }
}
