//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases()
        {
            this.Builds = new HashSet<Builds>();
        }
    
        public int CaseID { get; set; }
        public int ManufacturerID { get; set; }
        public string Model { get; set; }
        public int CaseFFID { get; set; }
        public int MaxGPULength { get; set; }
        public int MaxCoolers { get; set; }
        public bool CompatibilityATX { get; set; }
        public bool CompatibilityMicroATX { get; set; }
        public bool CompatibilityMiniATX { get; set; }
        public bool CompatibilityMiniITX { get; set; }
        public bool CompatibilityMiniSTX { get; set; }
        public bool CompatibilityEATX { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Builds> Builds { get; set; }
        public virtual CaseFormFactors CaseFormFactors { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
