//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Collections.Generic;

    public partial class CPUs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPUs()
        {
            this.Builds = new HashSet<Builds>();
        }

        public int CPUID { get; set; }
        public int ManufacturerID { get; set; }
        public int SocketID { get; set; }
        public string Model { get; set; }
        public int Cores { get; set; }
        public int Threads { get; set; }
        public decimal BaseClock { get; set; }
        public decimal BoostClock { get; set; }
        public int TDP { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Builds> Builds { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Sockets Sockets { get; set; }

        public string ManufacturerName
        {
            get
            {
                return Manufacturers.ManufacturerName;
            }
        }
    }
}
