//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        private static DatabaseEntities _context;
        public static DatabaseEntities GetContext()
        {
            if (_context == null)
                _context = new DatabaseEntities();
            return _context;
        }
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildCaseCooling> BuildCaseCooling { get; set; }
        public virtual DbSet<BuildRAMs> BuildRAMs { get; set; }
        public virtual DbSet<Builds> Builds { get; set; }
        public virtual DbSet<BuildStorages> BuildStorages { get; set; }
        public virtual DbSet<CaseCooling> CaseCooling { get; set; }
        public virtual DbSet<CaseFormFactors> CaseFormFactors { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<CoolingTypes> CoolingTypes { get; set; }
        public virtual DbSet<CPUCooling> CPUCooling { get; set; }
        public virtual DbSet<CPUs> CPUs { get; set; }
        public virtual DbSet<EfficiencyRatings> EfficiencyRatings { get; set; }
        public virtual DbSet<GPUMemoryTypes> GPUMemoryTypes { get; set; }
        public virtual DbSet<GPUs> GPUs { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<MotherboardFormFactor> MotherboardFormFactor { get; set; }
        public virtual DbSet<Motherboards> Motherboards { get; set; }
        public virtual DbSet<PowerSupplies> PowerSupplies { get; set; }
        public virtual DbSet<RAMs> RAMs { get; set; }
        public virtual DbSet<RAMTypes> RAMTypes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sockets> Sockets { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
        public virtual DbSet<StorageTypes> StorageTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
    }
}
