//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboards()
        {
            this.Builds = new HashSet<Builds>();
        }
    
        public int MotherboardID { get; set; }
        public int ManufacturerID { get; set; }
        public string Model { get; set; }
        public int SocketID { get; set; }
        public int RAMTypeID { get; set; }
        public int MotherboardFFID { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Builds> Builds { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MotherboardFormFactor MotherboardFormFactor { get; set; }
        public virtual RAMTypes RAMTypes { get; set; }
        public virtual Sockets Sockets { get; set; }
    }
}
